package net.boypika.pikaconfiga.config;

import java.io.*;
import java.util.*;

public class Config {
    private Properties properties = new Properties();
    private File propertiesFile;

    public Config(File file) {
        this.propertiesFile = file;
        if (file.exists()) {
            try {
                this.properties.load(new FileInputStream(file));
            } catch (Exception var3) {
                this.generate();
            }
        } else {
            this.generate();
        }

    }

    public void generate() {
        this.save();
    }

    public void save() {
        try {
            this.properties.store(new FileOutputStream(this.propertiesFile), "Generated By BoyPika Config");
        } catch (Exception var2) {
            this.generate();
        }

    }
    public String addComment(String comment) {
        try {
            return this.getString("", comment);
        } catch (Exception var4) {
            this.properties.setProperty("", comment);
            return comment;
        }
    }

    public String getString(String string, String string2) {
        if (!this.properties.containsKey(string)) {
            this.properties.setProperty(string, string2);
            this.save();
        }

        return this.properties.getProperty(string, string2);
    }

    public int setInteger(String string, int i) {
        try {
            return Integer.parseInt(this.getString(string, "" + i));
        } catch (Exception var4) {
            this.properties.setProperty(string, "" + i);
            return i;
        }
    }
    public int getInteger(String string){
        return Integer.parseInt(this.getString(string, ""));
    }

    public boolean getBoolean(String string, boolean bl) {
        try {
            return Boolean.parseBoolean(this.getString(string, "" + bl));
        } catch (Exception var4) {
            this.properties.setProperty(string, "" + bl);
            return bl;
        }
    }

    public void setBoolean(String string, boolean bl) {
        this.properties.setProperty(string, "" + bl);
        this.save();
    }
}

